'use strict';

module.exports = {
  en: {
    language: 'English',
    extension: 'Browser extension',
    reminder: 'Review the page before sharing.',
    useCases: 'For screen sharing and recordings.',
    result: {
      headline: ['Hide email addresses', 'before you share.'],
      description: 'Replace email addresses on the page with made-up ones. The rest stays readable.',
      before: 'Before',
      after: 'After Maskify',
      consistency: 'Repeated addresses get the same replacement.',
      action: 'Open Maskify and click',
      button: 'Mask Emails',
    },
    coverage: {
      headline: ['Email links and', 'form fields, too.'],
      description: 'Choose Mask Emails to replace addresses in all three places.',
      labels: ['Page text', 'Email links', 'Form fields'],
      captions: [
        'Other text stays as it is.',
        'Both the visible address and link destination change.',
        'Includes email fields and notes.',
      ],
    },
    controls: {
      headline: ['Choose the', 'replacement format.'],
      description: 'Set a domain and choose whether to add a number or a random initial.',
      marker: 'Mark replacements with ***.',
      caption: 'The preview updates as you change the settings.',
      domain: 'demo.test',
      preview: 'alice_r7***@demo.test',
    },
    demo: {
      directory: 'Team directory',
      count: '3 entries',
      name: 'Name',
      role: 'Role',
      email: 'Email',
      roles: ['Design', 'Engineering', 'Project lead'],
      summary: 'Project contact',
      project: 'Website refresh',
      owner: 'Project owner',
      questions: 'Questions about the launch?',
      reach: 'Reach Carla at',
      contact: 'Get in touch',
      linkIntro: 'Send the project brief to',
      linkNote: 'Email contact',
      details: 'Contact details',
      notes: 'Notes',
      noteText: 'Send the draft to carla@team.example before the review.',
    },
  },
  es: {
    language: 'Español',
    extension: 'Extensión del navegador',
    reminder: 'Revisa la página antes de compartirla.',
    useCases: 'Para compartir o grabar la pantalla.',
    result: {
      headline: ['Oculta las direcciones de correo', 'antes de compartir.'],
      description: 'Cambia las direcciones de correo de la página por otras inventadas, sin ocultar el resto.',
      before: 'Antes',
      after: 'Con Maskify',
      consistency: 'La misma dirección recibe el mismo reemplazo.',
      action: 'Abre Maskify y pulsa',
      button: 'Enmascarar correos',
    },
    coverage: {
      headline: ['También en enlaces', 'y formularios.'],
      description: 'Pulsa Enmascarar correos para sustituir las direcciones en estos tres lugares.',
      labels: ['Texto de la página', 'Enlaces de correo', 'Formularios'],
      captions: [
        'El resto del texto no cambia.',
        'Cambian la dirección visible y el destino del enlace.',
        'Incluye campos de correo y notas.',
      ],
    },
    controls: {
      headline: ['Elige el formato', 'de los reemplazos.'],
      description: 'Elige un dominio. Puedes agregar un número o una inicial aleatoria.',
      marker: 'Marca las direcciones sustituidas con ***.',
      caption: 'La vista previa cambia con tus ajustes.',
      domain: 'demo.test',
      preview: 'alicia_r7***@demo.test',
    },
    demo: {
      directory: 'Directorio del equipo',
      count: '3 registros',
      name: 'Nombre',
      role: 'Rol',
      email: 'Correo',
      roles: ['Diseño', 'Ingeniería', 'Coordinación'],
      summary: 'Contacto del proyecto',
      project: 'Renovación de la web',
      owner: 'Responsable del proyecto',
      questions: '¿Dudas sobre el lanzamiento?',
      reach: 'Escribe a Carla:',
      contact: 'Ponte en contacto',
      linkIntro: 'Envía el resumen del proyecto a',
      linkNote: 'Contacto por correo',
      details: 'Datos de contacto',
      notes: 'Notas',
      noteText: 'Envía el borrador a carla@team.example antes de la revisión.',
    },
  },
};
